//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarGenMerger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarGenMerger.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merges differing car generators from one or more &apos;source&apos; savefiles into one &apos;target&apos; savefile. Merging occurs by first comparing the car generators from the source files against the car generators in the target file for differences, then replacing the differing car generators in the target file with car generators from the source files..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cgmerge.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA Car Generator Merger Tool.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cgmerge [options] target source....
        /// </summary>
        public static string AppUsage {
            get {
                return ResourceManager.GetString("AppUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string AppUsagePrefix {
            get {
                return ResourceManager.GetString("AppUsagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Bad value for &apos;{0}&apos;..
        /// </summary>
        public static string ErrorText_BadOptionValue {
            get {
                return ResourceManager.GetString("ErrorText_BadOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to open file. ({0}).
        /// </summary>
        public static string ErrorText_FailedToOpenFile {
            get {
                return ResourceManager.GetString("ErrorText_FailedToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing value for &apos;{0}&apos;..
        /// </summary>
        public static string ErrorText_MissingOptionValue {
            get {
                return ResourceManager.GetString("ErrorText_MissingOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing required option &apos;{0}&apos;..
        /// </summary>
        public static string ErrorText_MissingRequiredOption {
            get {
                return ResourceManager.GetString("ErrorText_MissingRequiredOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing required argument..
        /// </summary>
        public static string ErrorText_MissingRequiredPositional {
            get {
                return ResourceManager.GetString("ErrorText_MissingRequiredPositional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Multiple values for option &apos;{0}&apos; have been provided..
        /// </summary>
        public static string ErrorText_RepeatedOption {
            get {
                return ResourceManager.GetString("ErrorText_RepeatedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown error. ({0}).
        /// </summary>
        public static string ErrorText_UnknownError {
            get {
                return ResourceManager.GetString("ErrorText_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown option &apos;{0}&apos;..
        /// </summary>
        public static string ErrorText_UnknownOption {
            get {
                return ResourceManager.GetString("ErrorText_UnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set whether to merge car generators from GTA3 or Vice City savefiles..
        /// </summary>
        public static string HelpText_Mode {
            get {
                return ResourceManager.GetString("HelpText_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the path to the resulting savefile. If not specified, the target file will be overwritten..
        /// </summary>
        public static string HelpText_Output {
            get {
                return ResourceManager.GetString("HelpText_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CSV file specifying the order in which to replace car generators. The columns are (priority,index) where &apos;priority&apos; represents the replacement order and &apos;index&apos; specifies the index of a car generator in the target save&apos;s car generator list. A priority of 0 is the highest priority. A negative priority will exclude row from replacement. If multiple rows share the same priority, one of the rows will be chosen at random and this process will repeat until all have been chosen exactly once. Lines beginning with [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpText_PriorityList {
            get {
                return ResourceManager.GetString("HelpText_PriorityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the collision radius. If two car generators are found within the collision radius, the merge process will be aborted..
        /// </summary>
        public static string HelpText_Radius {
            get {
                return ResourceManager.GetString("HelpText_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the in-game title of the target savefile..
        /// </summary>
        public static string HelpText_Title {
            get {
                return ResourceManager.GetString("HelpText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable verbose output for hackers..
        /// </summary>
        public static string HelpText_Verbose {
            get {
                return ResourceManager.GetString("HelpText_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}: Index exceeds maximum value of {2}..
        /// </summary>
        public static string WarningText_PriorityListIndexExceedsMaximum {
            get {
                return ResourceManager.GetString("WarningText_PriorityListIndexExceedsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}: Line is malformatted..
        /// </summary>
        public static string WarningText_PriorityListMalformedLine {
            get {
                return ResourceManager.GetString("WarningText_PriorityListMalformedLine", resourceCulture);
            }
        }
    }
}
